# Generated by Django 4.0.3 on 2022-03-11 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_squashed_0028_merge_20220311_0043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingnotes",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
