# Generated by Django 4.0.2 on 2022-02-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_feedbackform_acceptingsubmissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='acceptingSubmissionsUntil',
            field=models.DateTimeField(blank=True),
        ),
    ]
