# Generated by Django 4.0.2 on 2022-02-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_feedbackform_acceptingsubmissionsuntil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackform",
            name="acceptingSubmissionsUntil",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
