# Generated by Django 4.0.2 on 2022-02-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_feedbackform_acceptingsubmissionsuntil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="QuestionType",
        ),
    ]
