# Generated by Django 4.0.2 on 2022-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_rename_data_questions_type_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackform",
            name="allowsEditingSubmissions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedbackform",
            name="allowsMultipleSubmissions",
            field=models.BooleanField(default=True),
        ),
    ]
