# Generated by Django 4.0.2 on 2022-02-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_feedbackform_allowseditingsubmissions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultFeedbackForms",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.feedbackform",
                    ),
                ),
            ],
        ),
    ]
