# Generated by Django 4.0.2 on 2022-02-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequest",
            name="details",
            field=models.TextField(blank=True),
        ),
    ]
