# Generated by Django 4.0.2 on 2022-02-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_eventrequest_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventrequest",
            name="details",
        ),
    ]
