# Generated by Django 4.0.2 on 2022-02-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_remove_eventrequest_details"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventrequest",
            index=models.Index(
                fields=["type", "requested_by", "associated_topic"],
                name="events_even_type_id_16c464_idx",
            ),
        ),
    ]
