# Generated by Django 4.0.2 on 2022-02-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_remove_eventrequest_events_even_type_id_16c464_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="eventrequest",
            name="events_even_request_beb3ea_idx",
        ),
        migrations.AddConstraint(
            model_name="eventrequest",
            constraint=models.UniqueConstraint(
                fields=("requested_by", "associated_topic"), name="unique_request"
            ),
        ),
    ]
