# Generated by Django 4.0.2 on 2022-03-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_meetingnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingnotes',
            old_name='note',
            new_name='content',
        ),
    ]
