# Generated by Django 4.0.2 on 2022-03-10 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0024_rename_note_meetingnotes_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralFeedbackForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_for",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
