# Generated by Django 4.0.2 on 2022-03-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_generalfeedbackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalfeedbackform',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
