# Generated by Django 4.0.2 on 2022-03-10 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0026_generalfeedbackform_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingnotes',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='meetingnotes',
            name='mentor',
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
