# Generated by Django 4.0.2 on 2022-03-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_type_alter_eventrequest_type_and_more'),
        ('events', '0027_remove_meetingnotes_mentee_and_more'),
    ]

    operations = [
    ]
