# Generated by Django 4.0.2 on 2022-02-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.businessarea"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="people.usertype"
            ),
        ),
    ]
