# Generated by Django 4.0.2 on 2022-02-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usertopic",
            name="people_user_user_id_fe678a_idx",
        ),
        migrations.AddField(
            model_name="usertopic",
            name="usertype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.usertype",
            ),
        ),
        migrations.AddIndex(
            model_name="usertopic",
            index=models.Index(
                fields=["user", "topic", "usertype"],
                name="people_user_user_id_7f44ed_idx",
            ),
        ),
    ]
