# Generated by Django 4.0.2 on 2022-02-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_remove_usertopic_people_user_user_id_fe678a_idx_and_more"),
        ("people", "0002_user_bio_alter_user_business_area_and_more"),
    ]

    operations = []
