# Generated by Django 4.0.2 on 2022-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_user_last_login_user_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=False),
        ),
    ]
