# Generated by Django 4.0.2 on 2022-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_user_admin_user_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
