# Generated by Django 4.0.2 on 2022-02-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_user_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usertopic',
            name='people_user_user_id_7f44ed_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('MentorMentee', 'Mentormentee')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usertopic',
            name='usertype',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('MentorMentee', 'Mentormentee')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='usertopic',
            index=models.Index(fields=['user', 'topic', 'usertype'], name='people_user_user_id_092cdd_idx'),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
