# Generated by Django 4.0.2 on 2022-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_remove_usertopic_people_user_user_id_7f44ed_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mentor", "Mentor"),
                    ("Mentee", "Mentee"),
                    ("MentorMentee", "Mentor & Mentee"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usertopic",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("Mentor", "Mentor"),
                    ("Mentee", "Mentee"),
                    ("MentorMentee", "Mentor & Mentee"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
