# Generated by Django 4.0.2 on 2022-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_alter_user_user_type_alter_usertopic_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.CharField(max_length=500),
        ),
    ]
