# Generated by Django 4.0.2 on 2022-02-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_user_user_type_alter_usertopic_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planofactiontarget',
            name='achieved_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('MentorMentee', 'Mentor & Mentee'), ('None', 'Neither')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='usertopic',
            name='usertype',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('MentorMentee', 'Mentor & Mentee'), ('None', 'Neither')], max_length=50, null=True),
        ),
    ]
