# Generated by Django 4.0.2 on 2022-02-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_notification_title_alter_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
