# Generated by Django 4.0.2 on 2022-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_alter_user_user_type_alter_usertopic_usertype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planofactiontarget",
            name="achieved_at",
        ),
        migrations.AddField(
            model_name="planofactiontarget",
            name="achieved",
            field=models.BooleanField(default=False),
        ),
    ]
