# Generated by Django 4.0.2 on 2022-02-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_notification_link"),
        ("people", "0010_remove_planofactiontarget_achieved_at_and_more"),
    ]

    operations = []
